#include <getopt.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define EPISILON                                                               \
  0.000000001 // Tolerance value for the terms generated by the e^x function
              // approx.
#define OPTIONS "sctea" // input flags options stored in string

typedef enum TEST {
  SIN = 0,
  COS,
  TAN,
  EXP,
  ALL
} test; // User defined testing states to exclusively choose one test/

double normalize(double x) {
  if (x > 2 * M_PI) {
    while (x > 2 * M_PI) {
      x -= 2 * M_PI;
    }
  } else if (x < -2 * M_PI) {
    while (x < -2 * M_PI) {
      x += 2 * M_PI;
    }
  } else {
  }
  return x;
}

// Exponential function
double Exp(double x) {
  double solution = 1;
  int n = 1;
  double error = 1; // since x^0/0! is always 1
  while (error > EPISILON) {
    error *= x / n;    // computes each taylor term(x^n/n!) by mult by x/n
    solution += error; // Adds all taylor terms
    n++;
  }

  return solution; // returns x raised to the power of e
}

// Sin function
double Sin(double x) {
  x = normalize(x);
  double square_term = x * x;
  // Answer computed by Pade approximant programmed below.
  double answer =
      (x * ((square_term * (52785432 - 479249 * square_term) - 1640635920) *
                square_term +
            11511339840)) /
      (((18361 * square_term + 3177720) * square_term + 277920720) *
           square_term +
       11511339840);
  return answer; // Returns sin value evaluated at x.
}

// Cos function
double Cos(double x) {
  x = normalize(x);
  double square_term = x * x;
  // Answer computed by Pade approximant programmed below.
  double answer =
      ((square_term * (1075032 - 14615 * square_term) - 18471600) *
           square_term +
       39251520) /
      (((127 * square_term + 16632) * square_term + 1154160) * square_term +
       39251520);
  return answer; // Returns cos value evaluated at x
}

// Tan function
double Tan(double x) {
  x = normalize(x);
  double square_term = x * x;
  double fourth_term = square_term * square_term;
  double sixth_term = square_term * fourth_term;
  double eight_term = fourth_term * fourth_term;
  // Answer computed by Pade approximant programmed below.
  double answer =
      (x * (eight_term - (990 * sixth_term) + (135135 * fourth_term) -
            (4729725 * square_term) + 34459425)) /
      (45 * (eight_term - (308 * sixth_term) + (21021 * fourth_term) -
             (360360 * square_term) + 765765));
  return answer; // Returns tan value evaluated at x
}

// Exp simulation
void exp_test() {
  printf("x\tExp\t\tLibrary\t\tDifference\n"); // Print table format
  printf("-\t---\t\t-------\t\t----------\n"); // Print table format
  double result = 0;                           // stores program approximation
  double result_lib = 0;                       // stores math.h library value
  double diff = 0; // Difference between values above
  for (double x = 1; x <= 10;
       x +=
       0.1) { // For loop  iterating over specified domain over given interval
    // Computation of printing values at each given x
    result = Exp(x);
    result_lib = exp(x);
    diff = result - result_lib;
    printf("%.4lf\t%.8lf\t%.8lf\t%.10lf\n", x, result, result_lib,
           diff); // Printing function values at each domain interval
  }
  return;
}

// Sin simulation. (Follows same format and variable naming as exp_test()
// described above)
void sin_test() {
  printf("x\tSin\t\tLibrary\t\tDifference\n");
  printf("-\t---\t\t-------\t\t----------\n");
  double result = 0;
  double result_lib = 0;
  double diff = 0;
  for (double x = -(M_PI * 2); x <= (M_PI * 2 + 0.0001); x += (M_PI / 16)) {
    result = Sin(x);
    result_lib = sin(x);
    diff = result - result_lib;
    printf("%.4lf\t%.8lf\t%.8lf\t%.10lf\n", x, result, result_lib, diff);
  }
  return;
}

// Cos simulation (Follows same format and variable naming as exp_test()
// described above)
void cos_test() {
  printf("x\tCos\t\tLibrary\t\tDifference\n");
  printf("-\t---\t\t-------\t\t----------\n");
  double result = 0;
  double result_lib = 0;
  double diff = 0;
  for (double x = -(M_PI * 2); x <= (M_PI * 2 + 0.0001); x += (M_PI / 16)) {
    result = Cos(x);
    result_lib = cos(x);
    diff = result - result_lib;
    printf("%.4lf\t%.8lf\t%.8lf\t%.10lf\n", x, result, result_lib, diff);
  }
  return;
}

// Tan simulation (Follows same format and variable naming as exp_test()
// described above)
void tan_test() {
  printf("x\tTan\t\tLibrary\t\tDifference\n");
  printf("-\t---\t\t-------\t\t----------\n");
  double result = 0;
  double result_lib = 0;
  double diff = 0;
  double bound = M_PI / 2;
  for (double x = (-bound - 0.001); x <= (bound - 0.001);
       x += (M_PI / 16)) { // the 0.001 tolerance value to get closest tan value
                           // of pi/2   without getting undefined values.
    result = Tan(x);
    result_lib = tan(x);
    diff = result - result_lib;
    printf("%.4lf\t%.8lf\t%.8lf\t%.10lf\n", x, result, result_lib, diff);
  }
  return;
}

int main(int argc, char **argv) {
  test select_test; // variable to store defined test state
  int c = 0;        // variable to store different flags
  while ((c = getopt(argc, argv, OPTIONS)) !=
         -1) { // switch case between types of flags
    // each case will set testing state variable (select_test) to the desired
    // function simulation.
    switch (c) {
    case 's':
      select_test = SIN;
      break;
    case 'c':
      select_test = COS;
      break;
    case 't':
      select_test = TAN;
      break;
    case 'e':
      select_test = EXP;
      break;
    case 'a':
      select_test = ALL;
      break;
    default:
      break;
    }
  }
  if (argc == 1) {
    puts("Error: no arguments supplied!"); // Raise error if no flags are
                                           // inputted
    return -1;
  }

  // Switch statement to define what functions test(s) to run giving the testing
  // state determined in switch statement above
  switch (select_test) {
  case SIN:
    sin_test(); // Run sin simulation
    printf("\n");
    break;
  case COS:
    cos_test(); // Run cos simulation
    printf("\n");
    break;
  case TAN:
    tan_test(); // Run tan simulation
    printf("\n");
    break;
  case EXP:
    exp_test(); // Run exp simulation
    printf("\n");
    break;
  case ALL:
    // Run all simulations
    sin_test();
    cos_test();
    tan_test();
    exp_test();
    printf("\n");
    break;
  default:
    break;
  }

  return 0; // return success
}
