#include "providedCode/bf.h"
#include "bv.h"
#include <stdlib.h>

// Create bloom filter with slats.
BloomFilter *bf_create(uint32_t size) {
  BloomFilter *bf = (BloomFilter *)malloc(sizeof(BloomFilter));
  if (bf) {
    bf->primary[0] = 0xfc28ca6885711cf7; // U.S. Constitution
    bf->primary[1] = 0x2841af568222f773;
    bf->secondary[0] = 0x85ae998311115ae3; // Il nome della rosa
    bf->secondary[1] = 0xb6fac2ae33a40089;
    bf->tertiary[0] = 0xd37b01df0ae8f8d0; // The Cremation of Sam McGee
    bf->tertiary[1] = 0x911d454886ca7cf7;
    bf->filter = bv_create(size); // Create bitvector to store hash indexed bits
    return bf;                    // Return bloomfilter ptr
  }
  return (BloomFilter *)NIL;
}

// Delete filter
void bf_delete(BloomFilter *bf) {
  bv_delete(bf->filter); // Delete bitvector
  bf->filter = NULL;
  free(bf); // Free memory allocated to bloom filter.
  bf = NULL;
}

// Sets bit at hash index generated
void bf_insert(BloomFilter *b, char *key) {
  // Value moded by bitvector lenght to fit size.
  bv_set_bit(b->filter,
             hash(b->primary, key) %
                 bv_length(b->filter)); // primary hash value index bit set
  bv_set_bit(b->filter,
             hash(b->secondary, key) %
                 bv_length(b->filter)); // secondary hash value index bit set
  bv_set_bit(b->filter,
             hash(b->tertiary, key) %
                 bv_length(b->filter)); // tertiary hash vlaue bit set.
}

// Returns bitvector length
uint32_t bf_length(BloomFilter *b) { return (uint32_t)bv_length(b->filter); }

// Check if key exists in bloomfilter
bool bf_probe(BloomFilter *b, char *key) {
  if (bv_get_bit(b->filter, hash(b->primary, key) % bv_length(b->filter)) ==
      1) { // Check if hash index generated by key is set to 1 for all 3 salrs
    if (bv_get_bit(b->filter, hash(b->secondary, key) % bv_length(b->filter)) ==
        1) {
      if (bv_get_bit(b->filter,
                     hash(b->tertiary, key) % bv_length(b->filter)) == 1) {
        return true; // Return true if all 3 bits set to 1
      }
    }
  }
  return false;
}

// count all bits sets to 1
uint32_t bf_count(BloomFilter *b) {
  uint32_t set_count = 0;
  for (uint32_t k = 0; k < bf_length(b); k++) {
    if (bv_get_bit(b->filter, k) ==
        1) { // Check if bit at index is 1. Increment if true.
      set_count++;
    }
  }
  return set_count;
}
